using Speckle.ProxyGenerator.Extensions;
using Speckle.ProxyGenerator.Models;

namespace Speckle.ProxyGenerator.FileGenerators;

internal class ExtraFilesGenerator : IFileGenerator
{
    private const string Name = "Speckle.ProxyGenerator.Extra.g.cs";

    public FileData GenerateFile(bool supportsNullable)
    {
        return new FileData(
            $"{Name}",
            $@"//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by https://github.com/specklesystems/ProxyGenerator
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

{supportsNullable.IIf("#nullable enable")}
using System;

namespace Speckle.ProxyGenerator
{{
    [AttributeUsage(AttributeTargets.Interface)]
    internal sealed class ProxyAttribute : Attribute
    {{
        public Type Type {{ get; }}
        public ImplementationOptions Options {{ get; }}
        public ProxyClassAccessibility Accessibility {{ get; }}
        public string[]? MembersToIgnore {{ get; }}

        public ProxyAttribute(Type type) : this(type, ImplementationOptions.None, ProxyClassAccessibility.Public)
        {{
        }}

        public ProxyAttribute(Type type, ImplementationOptions options) : this(type, options, ProxyClassAccessibility.Public)
        {{
        }}

       	public ProxyAttribute(Type type, ProxyClassAccessibility accessibility) : this(type, ImplementationOptions.None, accessibility)
        {{
        }}

        public ProxyAttribute(Type type, ImplementationOptions options, ProxyClassAccessibility accessibility) : this(type, options, accessibility, null)
        {{
        }}

        public ProxyAttribute(Type type, string[]? membersToIgnore) : this(type, ImplementationOptions.None, ProxyClassAccessibility.Public, null)
        {{
        }}

        public ProxyAttribute(Type type, ImplementationOptions options, string[]? membersToIgnore) : this(type, options, ProxyClassAccessibility.Public, null)
        {{
        }}

        public ProxyAttribute(Type type, ImplementationOptions options, ProxyClassAccessibility accessibility, string[]? membersToIgnore)
        {{
            Type = type;
            Options = options;
            Accessibility = accessibility;
            MembersToIgnore = membersToIgnore;
        }}
    }}

    [Flags]
    internal enum ProxyClassAccessibility
    {{
        Public = 0,

        Internal = 1
    }}
    [Flags]
    internal enum ImplementationOptions
    {{
        None = 0,

        ProxyBaseClasses = 1,

        ProxyInterfaces = 2,

        UseExtendedInterfaces = 4,

        ProxyForBaseInterface = 8
    }}
{supportsNullable.IIf("#nullable restore")}
}}"
        );
    }
}
